name = "yishan-app"
compatibility_date = "2024-04-05"
pages_build_output_dir = "dist"

# Binding the D1 Database
# IMPORTANT: Run `npx wrangler d1 create yishan-db` to get your ID
# Then replace the empty string below with that ID.
[[d1_databases]]
binding = "DB"
database_name = "yishan-db"
database_id = "f3cf9afd-8bd1-4fa8-abf4-048d46e3edda" 
